version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb_container"
    volumes:
      - ./mongo-volume:/data/db
    command: mongod --port 21017
    ports:
      - "127.0.0.1:21017:21017"

  crypt-backend:
    image: rmaafs/crypt-me-api:latest
    ports:
      - "20203:20203"
    environment:
      VIRTUAL_HOST: api-crypt.rmaafs.com
      MONGO_PATH: "mongodb://mongodb:21017"
    restart: always
    depends_on:
      - mongodb

networks:
  default:
    name: nginx-proxy
    external: true
