version: "3"
services:
  mongodb:
    image: "mongo"
    container_name: "mongodb_container"
    environment:
      - MONGO_INITDB_DATABASE=crypt_db
      - MONGO_INITDB_ROOT_USERNAME=crypt_user
      - MONGO_INITDB_ROOT_PASSWORD=cryPt_p4ssw0rD
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - "27017-27019:27017-27019"

  crypt-backend:
    image: rmaafs/crypt-me-api:latest
    ports:
      - "20203:20203"

    environment:
      VIRTUAL_HOST: api-crypt.rmaafs.com
      MONGO_INITDB_DATABASE: "mongodb://mongodb:27017/?authSource=crypt_db&gssapiServiceName=mongodb"
    #env_file: /root/.env/crypt-me-api/secrets.env
    restart: always
    depends_on:
      - mongodb
    network_mode: bridge

volumes:
  mongo-volume:
